pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Hello from build stage'
                echo 'Hello from build stage 2'
            }
        }
        stage('Deploy') {
            steps {
                sh 'mv deploy'
                echo 'Hello from deploy stage'
            }
        }
        stage('Test') {
            steps {
                echo 'Hello from test stage'
            }
        }
        stage('Release') {
            steps {
                echo 'Hello from release stage'
            }
        }
    }
    post {
        failure {
            echo 'Pipeline failed'
        }
    }
}
